# Generated by Django 3.0.5 on 2020-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='type',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_type',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
