# Generated by Django 2.2.6 on 2020-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0002_type_unavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='slug',
        ),
        migrations.AlterField(
            model_name='type',
            name='name_type',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
