# Generated by Django 2.2.6 on 2020-05-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0003_auto_20200513_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
    ]
