# Generated by Django 2.2.6 on 2020-04-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0003_auto_20200429_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_picture',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteWeb.Loaner'),
        ),
        migrations.CreateModel(
            name='MaterialPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_picture', models.ImageField(blank=True, default='None/no-img.jpg', null=True, upload_to='media/')),
                ('material_barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteWeb.Material')),
            ],
        ),
    ]
