# Generated by Django 2.2.6 on 2020-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0009_auto_20200430_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_picture',
            field=models.ImageField(blank=True, default='None/no-img.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteWeb.Loaner'),
        ),
        migrations.DeleteModel(
            name='MaterialPicture',
        ),
    ]
